// Mocks generated by Mockito 5.4.6 from annotations
// in gossip_garden/test/features/plants/presentation/providers/chat_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gossip_garden/core/services/backend_chat_service.dart' as _i3;
import 'package:gossip_garden/features/plants/data/models/chat_dto.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChatMessageResponse_0 extends _i1.SmartFake
    implements _i2.ChatMessageResponse {
  _FakeChatMessageResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatHistoryResponse_1 extends _i1.SmartFake
    implements _i2.ChatHistoryResponse {
  _FakeChatHistoryResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BackendChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendChatService extends _i1.Mock
    implements _i3.BackendChatService {
  MockBackendChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ChatMessageResponse> chat({
    required String? plantId,
    required String? message,
    String? responseFormat = 'text',
    String? imageBase64,
    String? userAudioBase64,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chat,
          [],
          {
            #plantId: plantId,
            #message: message,
            #responseFormat: responseFormat,
            #imageBase64: imageBase64,
            #userAudioBase64: userAudioBase64,
          },
        ),
        returnValue: _i4.Future<_i2.ChatMessageResponse>.value(
            _FakeChatMessageResponse_0(
          this,
          Invocation.method(
            #chat,
            [],
            {
              #plantId: plantId,
              #message: message,
              #responseFormat: responseFormat,
              #imageBase64: imageBase64,
              #userAudioBase64: userAudioBase64,
            },
          ),
        )),
      ) as _i4.Future<_i2.ChatMessageResponse>);

  @override
  _i4.Future<_i2.ChatHistoryResponse> getHistory(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [plantId],
        ),
        returnValue: _i4.Future<_i2.ChatHistoryResponse>.value(
            _FakeChatHistoryResponse_1(
          this,
          Invocation.method(
            #getHistory,
            [plantId],
          ),
        )),
      ) as _i4.Future<_i2.ChatHistoryResponse>);
}
